const musicCatalog = [
    {
        "genre": "Pop",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/05/29",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/al borde de tu brillo.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3408172389",
        "title": "al borde de tu brillo"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/all around if you want.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375032712",
        "title": "all around if you want"
    },
    {
        "genre": "Pop / Jazz-Rock",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/08/13",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/and there you are.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "and there you are"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/AS WE FALL.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417132704",
        "title": "as we fall"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/05/29",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/backing go home.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3408172083",
        "title": "backing go home"
    },
    {
        "genre": "Pop, Jazz Cumbia",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/08/13",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/bajo el asfalto.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "bajo el asfalto"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/ball in play.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410913047",
        "title": "ball in play"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/Banana split.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417133423",
        "title": "banana split"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/bass stand yeah.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410913003",
        "title": "bass stand yeah"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/black and grey.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375033486",
        "title": "black and grey"
    },
    {
        "genre": "Rock",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/02/17",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/blanco arde negro quema.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3385521080",
        "title": "blanco arde negro quema"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/bloody lukas.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912975",
        "title": "bloody lukas"
    },
    {
        "genre": "Smooth Jazz Funky",
        "wav": "assets/audio_unificado/booking of the kindom.wav",
        "mood": "Premium",
        "regDate": "2026/08/13",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/booking of the kindom.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "booking of the kindom"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/books forever.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912873",
        "title": "books forever"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/Brake on the stars.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417133183",
        "title": "brake on the stars"
    },
    {
        "genre": "Smooth Jazz Bossa",
        "wav": "assets/audio_unificado/brotherhood without mercy.wav",
        "mood": "Premium",
        "regDate": "2026/08/14",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/brotherhood without mercy.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "brotherhood without mercy"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/bruma.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912408",
        "title": "bruma"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/Calles que respiran.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417132840",
        "title": "calles que respiran"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/CELTIC WHISTLE.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417131949",
        "title": "celtic whistle"
    },
    {
        "genre": "Bossanova",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/chrome rhythms.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912782",
        "title": "chrome rhythms"
    },
    {
        "genre": "Smooth Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/close your feelings extended.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375032789",
        "title": "close yours feelings (extended)"
    },
    {
        "genre": "Jazz rock Progresive",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/08/14",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/cloud kisses.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "cloud kisses"
    },
    {
        "genre": "Smooth Jazz Soul",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/08/14",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/cold fries and maybe lies.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "cold fries and maybe lies"
    },
    {
        "genre": "Pop-rock Funk",
        "wav": "assets/audio_unificado/corazón abierto.wav",
        "mood": "Premium",
        "regDate": "2026/08/14",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/corazón abierto.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "corazón abierto"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/corazón roto en happywood land.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "corazón roto en happywood land"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/cruza, rompe la distancia.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "cruza, rompe la distancia"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/cuando caigo dentro..mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "cuando caigo dentro."
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/04/29",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/day long day.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T340150944",
        "title": "day long day"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/demo track.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "demo track"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/deprisa, ven despacio.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912691",
        "title": "deprisa, ven despacio"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/digital mirage over.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "digital mirage over"
    },
    {
        "genre": "Pop-Rock / Balada",
        "wav": "assets/audio_unificado/donde el silencio aprende.wav",
        "mood": "Premium",
        "regDate": "2026/08/14",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/donde el silencio aprende.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "donde el silencio aprende"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/Down, or middle up.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417132362",
        "title": "down or middle up"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/dragon lands.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912613",
        "title": "dragon lands"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/Duck, Frog and me.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417151210",
        "title": "duck frog and me"
    },
    {
        "genre": "Pop",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/El horizonte se rompe.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417151389",
        "title": "el horizonte se rompe"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/el lugar que no se apaga.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "el lugar que no se apaga"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/entre neones.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "entre neones"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/08/02",
        "folders": [],
        "registered": true,
        "mp3": null,
        "authors": "Eduardo Ramírez",
        "iswc": "T3421767337",
        "title": "everything changes"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/envido en ti.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "envido en ti"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/eres hielo que arde en mi pecho.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "eres hielo que arde en mi pecho"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/feel your dreams.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912306",
        "title": "feel your dreams"
    },
    {
        "genre": "Pop",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/FIN DEL JUEGO.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417151163",
        "title": "fin del juego"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/08/02",
        "folders": [],
        "registered": true,
        "mp3": null,
        "authors": "Eduardo Ramírez",
        "iswc": "T3421767462",
        "title": "fire and roses"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/flock and road.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "flock and road"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2025/12/20",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/groove or not.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3371887371",
        "title": "groove or not"
    },
    {
        "genre": "Pop-Rock / Balada",
        "wav": "assets/audio_unificado/hay amores que solo aprenden a doler.wav",
        "mood": "Premium",
        "regDate": "2026/08/13",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/hay amores que solo aprenden a doler.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "hay amores que solo aprenden a doler"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/heavens glow.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375033544",
        "title": "heavens glow"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/how many times, sheep.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417151049",
        "title": "how many times sheep"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/I'm in the kitchen.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417150422",
        "title": "i m in the kitchen"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/ikeep walking.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3384142416",
        "title": "ikeep walking"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/07/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/Impracticable.mp3",
        "authors": "Eduardo Luis Ramírez",
        "iswc": "T3417151312",
        "title": "impracticable"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/jungle bells.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "jungle bells"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/leftover fries and midnight lies.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "leftover fries and midnight lies"
    },
    {
        "genre": "Pop",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/05/09",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/los que quedan de verdad.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3404724223",
        "title": "los que quedan de verdad"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/lotus play.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912259",
        "title": "lotus play"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/love fusion.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "love fusion"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/macao no es lao.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912180",
        "title": "macao no es lao"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/man island beach.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375032892",
        "title": "man island beach"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/master duke.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "master duke"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/me estremezco.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "me estremezco"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/me quitas todo.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "me quitas todo"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2025/12/22",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/meanwhile i love you.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3371895368",
        "title": "meanwhile i love you"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/medianoche en la terraza.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375033715",
        "title": "medianoche en la terraza"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/mellow stroll.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "mellow stroll"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/midnight lies.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "midnight lies"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/moonbeam dive.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "moonbeam dive"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/morning aproach.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "morning aproach"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/much time ago.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912066",
        "title": "much time ago"
    },
    {
        "genre": "Pop",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/07",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/nada.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410476330",
        "title": "nada"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/no me comas la cabeza.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "no me comas la cabeza"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/on the second verse.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "on the second verse"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/orange & yellow.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "orange & yellow"
    },
    {
        "genre": "Pop",
        "wav": "assets/Piso el acelerador.wav",
        "mood": "Premium",
        "regDate": "2026/08/02",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/piso el acelerador.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3420235996",
        "title": "piso el acelerador"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/plastic hard.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912555",
        "title": "plastic hard"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/please come back.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "please come back"
    },
    {
        "genre": "Funky",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/03/07",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/pulso a pulso.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3390173516",
        "title": "pulso a pulso"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/rompe la distancia.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "rompe la distancia"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/saxo by the clouds.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375033771",
        "title": "saxo by the clouds"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/saxophone serenade.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375032610",
        "title": "saxophone serenade"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/secret of velvet.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375033259",
        "title": "secret of velvet"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/seventy.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "seventy"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/seventy instrumental.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "seventy instrumental"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/seventy years.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "seventy years"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/sharp echoes.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "sharp echoes"
    },
    {
        "genre": "Jazz",
        "wav": "assets/audio/She Walks Untamed.wav",
        "mood": "Premium",
        "regDate": "2026/08/02",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/She walks or they.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3421797306",
        "title": "she walks or they"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/si algún día regresas.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "si algún día regresas"
    },
    {
        "genre": "Rock",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/02/17",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/si arde la senda.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3385521148",
        "title": "si arde la senda"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/04/19",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/side by side.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3399655422",
        "title": "side by side"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/siempre te amaré.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "siempre te amaré"
    },
    {
        "genre": "Bossanova",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/02/09",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/sigo caminando.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3383841729",
        "title": "sigo caminando"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/soft corners.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375033453",
        "title": "soft corners"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/take me.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "take me"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/take me where the night.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "take me where the night"
    },
    {
        "genre": "Pop",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/04/16",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/tanto drama por nada.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3399081182",
        "title": "tanto drama por nada"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/tatum screen.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410911961",
        "title": "tatum screen"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/te sigo en el silencio.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "te sigo en el silencio"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/the more lies you tell, the more i believe you..mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "the more lies you tell, the more i believe you."
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/the price you pay, provided that....mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "the price you pay, provided that..."
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/02",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/the scent of velvet.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3373873162",
        "title": "the scent of velvet"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/there are no wolves without sheep.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "there are no wolves without sheep"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/todo encaja.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "todo encaja"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/todo se curva.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "todo se curva"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/tujazzy socu.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "tujazzy socu"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/viejas lluvias.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "viejas lluvias"
    },
    {
        "genre": "Rock",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/02/17",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/viejos inviernos.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3385521206",
        "title": "viejos inviernos"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/vivo con el corazón abierto.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "vivo con el corazón abierto"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/voices for dreams.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375032972",
        "title": "voices for dreams"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/03/07",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/when the wind is pink.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3390173470",
        "title": "when the wind is pink"
    },
    {
        "genre": "Funky",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/03/27",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/wild and free.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3393999350",
        "title": "wild and free"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/06/10",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/without a trace of barbarism.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3410912497",
        "title": "without a trace of barbarism"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/03",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/woman on the island beach.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3375033077",
        "title": "woman on the island beach"
    },
    {
        "genre": "Alternativo",
        "wav": null,
        "mood": "Premium",
        "regDate": "",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/woodstock tigre celebration.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "woodstock tigre celebration"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/01/30",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/y llego zaawi.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3380981982",
        "title": "y llego zaawi"
    },
    {
        "genre": "Funky",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/03/27",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/yes chester, i feel.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3393999554",
        "title": "yes chester, i feel"
    },
    {
        "genre": "Jazz",
        "wav": null,
        "mood": "Premium",
        "regDate": "2026/05/29",
        "folders": [],
        "registered": true,
        "mp3": "assets/audio_unificado/a donde bass.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "T3408172743",
        "title": "¿a donde bass?"
    },
    {
        "genre": "Jazz-Rock funk",
        "wav": "assets/audio_unificado/seeking a harbor.wav",
        "mood": "Premium",
        "regDate": "2026/08/15",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/seeking a harbor.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "seeking a harbor"
    },
    {
        "genre": "Jazz-Rock / Fusion",
        "wav": "assets/audio_unificado/athenea me llama.wav",
        "cover": "assets/img/portada_athenea_me_llama.jpeg",
        "mood": "Premium",
        "regDate": "2026/08/15",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/athenea me llama.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "athenea me llama"
    },
    {
        "genre": "Jazz-Rock Funk",
        "wav": "assets/audio_unificado/busco un refugio.wav",
        "mood": "Premium",
        "regDate": "2026/08/15",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/busco un refugio.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "busco un refugio"
    },
    {
        "genre": "Smooth Jazz / Pop-Rock",
        "wav": "assets/audio_unificado/tan cerca del mar.wav",
        "cover": "assets/img/portada_tan_cerca_del_mar.jpeg",
        "mood": "Premium",
        "regDate": "2026/08/15",
        "folders": [],
        "registered": false,
        "mp3": "assets/audio_unificado/tan cerca del mar.mp3",
        "authors": "Eduardo Ramírez",
        "iswc": "",
        "title": "tan cerca del mar"
    }
];
